server:
  port: 8080
#spring:
#  profiles:
#    active: dev
---
server:
     port: 8082
     servlet:
       context-path: /wm
spring:
  profiles: dev
debug: false
---
server:
  port: 8083
spring:
  profiles: prod